# Generated by Django 5.1 on 2025-04-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_room_department'),
        ('services', '0004_category_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название счёта')),
                ('provider', models.CharField(max_length=100, verbose_name='Платёжная система (например, Bakai, mbank)')),
                ('payout_token', models.CharField(max_length=255, verbose_name='Токен для выплат')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Счёт для выплат',
                'verbose_name_plural': 'Счета для выплат',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='payout_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.payoutaccount', verbose_name='Счёт для выплат'),
        ),
    ]
