# Generated by Django 5.1 on 2025-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_payoutaccount_service_payout_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutaccount',
            name='provider',
            field=models.CharField(choices=[('Bakai', 'Bakai')], max_length=100, verbose_name='Платёжная система'),
        ),
    ]
