# Generated by Django 5.1 on 2025-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_payoutaccount_payout_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_note',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к оказанию'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_provided',
            field=models.BooleanField(default=False, verbose_name='Услуга оказана'),
        ),
    ]
