# Generated by Django 5.1 on 2025-07-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_service_note_service_service_provided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_note',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_provided',
        ),
    ]
