# Generated by Django 5.1 on 2025-07-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organization_email'),
        ('services', '0009_remove_service_service_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название группы')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название группы')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_groups', to='organizations.organization', verbose_name='Организация')),
                ('services', models.ManyToManyField(blank=True, related_name='service_groups', to='services.service', verbose_name='Услуги')),
            ],
        ),
    ]
