# Generated by Django 5.1 on 2025-07-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicegroup',
            options={'verbose_name': 'Группа услуг', 'verbose_name_plural': 'Группы услуг'},
        ),
    ]
