# Generated by Django 5.1 on 2025-07-31 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_servicegroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма'),
        ),
    ]
