# Generated by Django 5.1 on 2025-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_organization'),
        ('services', '0002_delete_servicestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.service', verbose_name='Услуги'),
        ),
    ]
