# Generated by Django 5.1 on 2025-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('accountant', 'Бухгалтер'), ('doctor', 'Врач'), ('superadmin', 'Супер Админ'), ('admin', 'Админ')], default='doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('working', 'Работает'), ('fired', 'Уволен')], default='working', max_length=50, verbose_name='Статус (работает/уволен)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
