# Generated by Django 5.1 on 2025-03-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_role_alter_user_status_and_more'),
        ('organizations', '0003_remove_room_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.department', verbose_name='Отдел'),
        ),
    ]
