# Generated by Django 5.1 on 2025-03-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_patient_first_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='services',
        ),
    ]
