# Generated by Django 5.1 on 2025-03-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_department_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='passport_id',
            new_name='passport_number',
        ),
    ]
