# Generated by Django 5.1 on 2025-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_passport_id_patient_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='passport_photo',
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/passport_photos/%Y/%m/%d/', verbose_name='Фото паспорта - задняя'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/passport_photos/%Y/%m/%d/', verbose_name='Фото паспорта - передняя'),
        ),
    ]
