# Generated by Django 5.1 on 2025-03-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_patient_passport_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birthdate',
            new_name='date_of_birth',
        ),
    ]
