# Generated by Django 5.1 on 2025-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_options_remove_patient_photo_and_more'),
        ('organizations', '0007_room_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
        migrations.AddField(
            model_name='user',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='organizations.room', verbose_name='Кабинеты'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
