# Generated by Django 5.1 on 2025-05-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_room_user_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rooms',
        ),
    ]
