# Generated by Django 5.1 on 2025-07-31 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_user_rooms'),
        ('services', '0012_servicegroup_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Категория услуг, которую пользователь имеет право предоставлять или редактировать.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category', verbose_name='Категория услуг'),
        ),
    ]
