# Generated by Django 5.1 on 2025-08-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_service_category'),
        ('services', '0012_servicegroup_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service_category',
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Услуги, которые пользователь имеет право предоставлять', related_name='user_services', to='services.service', verbose_name='Услуги'),
        ),
    ]
