# Generated by Django 5.1 on 2025-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_user_service_category_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='passport_front_photo',
            field=models.ImageField(default=1, upload_to='patients/passport_photos/%Y/%m/%d/', verbose_name='Фото паспорта - передняя'),
            preserve_default=False,
        ),
    ]
