# Generated by Django 5.1 on 2025-03-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=50, verbose_name='Действие')),
                ('entity', models.CharField(max_length=50, verbose_name='Сущность')),
                ('entity_id', models.IntegerField(verbose_name='ID сущности')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('user_type', models.CharField(choices=[('patient', 'Пациент'), ('staff', 'Сотрудник')], max_length=50, verbose_name='Тип пользователя')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительные детали')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Старые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время действия')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
            },
        ),
    ]
