# Generated by Django 5.1 on 2025-03-22 21:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_passport_id_patient_passport_number'),
        ('organizations', '0007_room_department'),
        ('transactions', '0002_alter_transaction_pay_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('pay_method', models.CharField(choices=[('cash', 'Наличные'), ('bakai_bank', 'Bakai Bank')], max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], max_length=50, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата транзакции')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Организация')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.patient', verbose_name='Пациент')),
                ('staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'historical Транзакция',
                'verbose_name_plural': 'historical Транзакции',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
