# Generated by Django 5.1 on 2025-03-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_historicaltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionservice',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='transactions.transaction', verbose_name='Транзакция'),
        ),
    ]
