# Generated by Django 5.1 on 2025-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactionservice_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionservice',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена услуги'),
        ),
    ]
