# Generated by Django 5.1 on 2025-03-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_description_en_service_description_ky_and_more'),
        ('transactions', '0006_transactionservice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Услуга'),
        ),
    ]
