# Generated by Django 5.1 on 2025-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transactionservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='status',
            field=models.CharField(choices=[('success', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], default='pending', max_length=50, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], default='pending', max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
