# Generated by Django 5.1 on 2025-05-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_historicaltransaction_pay_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Платежная ссылка'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Платежная ссылка'),
        ),
    ]
