# Generated by Django 5.1 on 2025-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_historicaltransaction_payment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='service_note',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий врача'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='service_provided',
            field=models.BooleanField(default=False, verbose_name='Услуга оказана'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_note',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий врача'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_provided',
            field=models.BooleanField(default=False, verbose_name='Услуга оказана'),
        ),
    ]
