# Generated by Django 5.1 on 2025-07-31 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_historicaltransaction_service_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='service_note',
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='service_provided',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service_note',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service_provided',
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provided_services', to=settings.AUTH_USER_MODEL, verbose_name='Поставщик услуги'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='service_note',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий врача'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='service_provided',
            field=models.BooleanField(default=False, verbose_name='Услуга оказана'),
        ),
    ]
