# Generated by Django 5.1 on 2025-07-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicegroup_total_price'),
        ('transactions', '0012_remove_historicaltransaction_service_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionservice',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category'),
        ),
    ]
