# Generated by Django 5.1 on 2025-08-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transactionservice_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionservice',
            name='service_category',
        ),
        migrations.AlterField(
            model_name='transactionservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provided_services', to=settings.AUTH_USER_MODEL, verbose_name='Кто оказал услугу'),
        ),
    ]
