# Generated by Django 5.1 on 2025-03-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название здания')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес здания')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/%Y/%m', verbose_name='Логотип')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вебсайт')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Логотип отдела')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='Номер комнаты')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
