# Generated by Django 5.1 on 2025-03-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_room_options_alter_room_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='department',
        ),
    ]
