# Generated by Django 5.1 on 2025-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_room_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название отдела'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название отдела'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название отдела'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название организации'),
        ),
    ]
