# Generated by Django 5.1 on 2025-03-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_building_address_en_building_address_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='building',
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Здание'),
            preserve_default=False,
        ),
    ]
