# Generated by Django 5.1 on 2025-03-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_department_building_department_organization'),
        ('services', '0003_service_description_en_service_description_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
    ]
