# Generated by Django 5.1 on 2025-05-03 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_room_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'doctor'}, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='Врачи'),
        ),
    ]
