# Generated by Django 5.1 on 2025-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на вебсайт'),
        ),
    ]
