# Generated by Django 5.1 on 2025-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organization_email'),
        ('services', '0010_servicegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='service_groups',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='services.servicegroup', verbose_name='Группы услуг'),
        ),
        migrations.AlterField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='rooms_services', to='services.service', verbose_name='Услуги'),
        ),
    ]
